---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: spring-boot-kubernetes
        version: 6.1.0
      name: spring-boot-kubernetes
    spec:
      ports:
        - name: http
          port: 8080
          protocol: TCP
          targetPort: 8080
          nodePort: 31000
      type: NodePort
      selector:
        app: spring-boot-kubernetes
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: spring-boot-kubernetes
        version: 6.1.0
      name: spring-boot-kubernetes
    spec:
      replicas: 1
      revisionHistoryLimit: 2
      selector:
        matchLabels:
          app: spring-boot-kubernetes
      template:
        metadata:
          labels:
            app: spring-boot-kubernetes
            version: 6.1.0
        spec:
          containers:
            - name: spring-boot-kubernetes
              image: ashutoshsahoo/spring-boot-kubernetes:6.1.0
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  memory: "1Gi"
                  cpu: "1"
                requests:
                  memory: "100Mi"
                  cpu: "100m"
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
