apiVersion: v1
kind: Service
metadata:
  name: spring-boot-kubernetes
  labels:
    app: spring-boot-kubernetes
    service: spring-boot-kubernetes
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: spring-boot-kubernetes
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-boot-kubernetes
  labels:
    account: spring-boot-kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-kubernetes-v5
  labels:
    app: spring-boot-kubernetes
    version: 5.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-kubernetes
      version: 5.0.0
  template:
    metadata:
      labels:
        app: spring-boot-kubernetes
        version: 5.0.0
    spec:
      serviceAccountName: spring-boot-kubernetes
      containers:
        - name: spring-boot-kubernetes
          image: ashutoshsahoo/spring-boot-kubernetes:5.0.0
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "100Mi"
              cpu: "100m"
          ports:
            - name: http
              containerPort: 8080
          securityContext:
            runAsUser: 1000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-kubernetes-v6
  labels:
    app: spring-boot-kubernetes
    version: 6.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-kubernetes
      version: 6.0.0
  template:
    metadata:
      labels:
        app: spring-boot-kubernetes
        version: 6.0.0
    spec:
      serviceAccountName: spring-boot-kubernetes
      containers:
        - name: spring-boot-kubernetes
          image: ashutoshsahoo/spring-boot-kubernetes:6.0.0
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "100Mi"
              cpu: "100m"
          ports:
            - name: http
              containerPort: 8080
          securityContext:
            runAsUser: 1000
---

